# Netlify config for Angular (monorepo subfolder)
[build]
  base = "loja-ng"
  command = "npm ci && npm run build"
  publish = "dist/loja-ng"

# Ensure the correct environment file is used based on branch
[context.production.environment]
  BRANCH = "prod"

[context.branch-deploy.environment]
  BRANCH = "dev"

# SPA fallback (optional, _redirects file already handles this)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
