export interface Produto {
  id?: number;
  nome: string;
  marca: string;
  slug?: string;
  descricao: string;
  descricaoCurta?: string;
  categorias?: string[];
  objetivos?: string[];
  peso: string;
  sabor?: string;
  preco: number;
  precoDesconto?: number;
  porcentagemDesconto?: string;
  custo?: number;
  fornecedor?: string;
  lucroEstimado?: number;
  statusAprovacao?: string;
  tamanhoPorcao?: string;
  imagemMimeType?: string;
  imagemBase64?: string;
  galeriaMimeTypes?: string[];
  galeriaBase64?: string[];
  galeria?: string[];
  imagem?: string;
  ativo?: boolean;
  destaque?: boolean;
  disponibilidade?: 'em_estoque' | 'por_encomenda' | 'nao_disponivel';
  estoque?: number;
  estoqueMinimo?: number;
  estoqueMaximo?: number;
  localizacaoFisica?: string;
  codigoBarras?: string;
  dimensoes?: {
    altura: number | null;
    largura: number | null;
    profundidade: number | null;
  };
  restricoes?: string[];
  tabelaNutricional?: any;
  modoDeUso?: string;
  palavrasChave?: string[];
  avaliacoes?: {
    media: number | null;
    comentarios: string[];
  };
  dataCadastro?: string | Date;
  dataUltimaAtualizacao?: string | Date;
  dataValidade?: string | Date;
  fornecedorId?: number;
  cnpjFornecedor?: string;
  contatoFornecedor?: string;
  prazoEntregaFornecedor?: string;
  quantidadeVendida?: number;
  vendasMensais?: number[];
}
